# Generated by Django 4.2.10 on 2025-05-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_last_seen_masterclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_mailing_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
