# Generated by Django 4.2.10 on 2025-05-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_phone'),
        ('users', '0004_update_gender_values'),
    ]

    operations = [
    ]
