# Generated by Django 4.2.10 on 2025-05-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20250518_1816'),
        ('users', '0005_update_gender_values'),
    ]

    operations = [
    ]
