# Generated by Django 4.2.10 on 2025-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='amount',
            field=models.DecimalField(choices=[(1000, '1000 RUB'), (2000, '2000 RUB'), (3000, '3000 RUB'), (5000, '5000 RUB'), (10000, '10000 RUB')], decimal_places=2, max_digits=10),
        ),
    ]
