# Generated by Django 4.2.10 on 2025-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='price',
        ),
        migrations.AddField(
            model_name='masterclass',
            name='bucket_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
