# Generated by Django 4.2.10 on 2025-05-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0002_remove_masterclass_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='occupied_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='address',
            field=models.CharField(blank=True, help_text='Address where the masterclass will be held', max_length=500),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='max_seats',
            field=models.PositiveIntegerField(default=20, help_text='Maximum number of seats available'),
        ),
    ]
