# Generated by Django 4.2.10 on 2025-05-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0003_event_occupied_seats_masterclass_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterclass',
            old_name='bucket_list',
            new_name='bucket_link',
        ),
        migrations.RenameField(
            model_name='masterclass',
            old_name='address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='masterclass',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='masterclass',
            old_name='description',
            new_name='short_description',
        ),
    ]
