# Generated by Django 4.2.10 on 2025-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0004_rename_bucket_list_masterclass_bucket_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='details',
            field=models.JSONField(default=list, help_text='List of details about the masterclass'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Dictionary of parameters with their values'),
        ),
    ]
