# Generated by Django 4.2.10 on 2025-05-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0005_masterclass_details_masterclass_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
