# Generated by Django 4.2.10 on 2025-05-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0006_masterclass_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='score_product_page',
            field=models.IntegerField(default=0, help_text='Оценка страницы продукта (0-100)'),
        ),
    ]
