# Generated by Django 4.2.10 on 2025-05-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0007_masterclass_score_product_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='bucket_link',
            field=models.JSONField(default=list, help_text="List of image URLs in format [{'url': 'https://...'}]"),
        ),
    ]
