# Generated by Django 4.2.10 on 2025-05-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0008_alter_masterclass_bucket_link'),
        ('orders', '0004_order_comment_order_email_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterclasses.event'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
